[package]
name = "powerbaby-protocol"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
naia-bevy-shared = { workspace = true }
